name: Actions for push events

on:
  push:
    paths:
      - ".github/**"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"

concurrency:
  group: "on-push-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  test:
    name: Test Python package
    uses: ./.github/workflows/test.yaml
    with:
      python-version: "3.14"
      coverage: ${{ github.ref_name == 'main' }}
      environment: "default"
    secrets: inherit

  cross_version_test:
    name: Test Python package (Cross version)
    if: ${{ github.ref_name == 'main' }}
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    uses: ./.github/workflows/test.yaml
    with:
      python-version: ${{ matrix.python-version }}
      coverage: false
      environment: "default"
    secrets: inherit
