name: Publish Python package

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true
      environment:
        type: string
        required: true
      project-url:
        type: string
        required: true

jobs:

  publish:
    name: Publish Python package
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.project-url }}
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync

      - name: Build package distributions
        run: uv build

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ vars.REPOSITORY_URL }}