name: Test publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish Python package
    uses: ./.github/workflows/publish.yaml
    with:
      environment: "testpypi"
      python-version: "3.14"
    permissions:
      id-token: write
      contents: read